FROM archlinux:latest

RUN pacman -Syu --noconfirm && \
    pacman -S --noconfirm \
        rust \
        xorg-server-xvfb \
        pkgconf gcc \
    && pacman -Scc --noconfirm

WORKDIR /app

ENTRYPOINT ["xvfb-run", "--auto-servernum", "--server-args=-screen 0 1024x768x24", "cargo", "test", "--", "--test-threads=1"]
