// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ModuleCategory = "system" | "hardware" | "network" | "audio" | "power" | "time" | "workspace" | "window" | "tray" | "weather" | "productivity" | "media" | "custom";
