// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CategoryInfo } from "./CategoryInfo";
import type { RegistryModule } from "./RegistryModule";

export type RegistryIndex = { version: number, modules: Array<RegistryModule>, categories: { [key in string]?: CategoryInfo }, };
