// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ModuleCategory } from "./ModuleCategory";
import type { ModuleUuid } from "./ModuleUuid";
import type { ModuleVersion } from "./ModuleVersion";

export type RegistryModule = { uuid: ModuleUuid, name: string, description: string, author: string, category: ModuleCategory, icon: string | null, screenshot: string | null, repo_url: string, downloads: bigint, version: ModuleVersion | null, last_updated: string | null, rating: number | null, verified_author: boolean, tags: Array<string>, checksum: string | null, };
