// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ReviewUser } from "./ReviewUser";

export type Review = { id: bigint, rating: number, title: string | null, body: string | null, helpful_count: bigint, user: ReviewUser, created_at: string, updated_at: string | null, };
