// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RegistryModule } from "./RegistryModule";

export type AuthorProfile = { modules: Array<RegistryModule>, id: bigint, username: string, display_name: string | null, avatar_url: string | null, bio: string | null, website_url: string | null, verified_author: boolean, module_count: bigint, created_at: string, };
